import BackgroundImage from "public/images/background.jpg";
import Image from "next/image";
import "src/styles/globals.css";

import MySessionProvider from "@/lib/session.provider";
import { getServerSession } from "next-auth";
import MainNav from "@/components/@main/main.nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  auth,
  main,
}: {
  auth: React.ReactNode;
  main: React.ReactNode;
  children: React.ReactNode;
}) {
  const data = await getServerSession();
  return (
    <html lang="en">
      <body>
        <MySessionProvider>
          <Image
            fill={true}
            src={BackgroundImage}
            alt={"background image"}
            style={{
              position: "absolute",
              zIndex: 0,
            }}
          />
          {data !== null ? (
            <header>
              <MainNav />
            </header>
          ) : null}
          {data !== null ? main : auth}
          {children}
        </MySessionProvider>
      </body>
    </html>
  );
}
