import BackgroundImage from "public/images/background.jpg";
import Image from "next/image";
import "src/styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Image
          fill={true}
          src={BackgroundImage}
          alt={"background image"}
          style={{
            position: "absolute",
            zIndex: 0,
          }}
        />
        {children}
      </body>
    </html>
  );
}
